---
- name: Install OpenJDK, Maven, Git and Build project
  hosts: build
  become: yes

  tasks:
  - name: Install OpenJDK
    apt:
     name: default-jdk
     state: present

  - name: Install Maven
    apt:
     name: maven
     state: present
     
  - name: Install Git
    apt:
     name: git
     state: present

  - name: Clone git project
    git:
     repo: https://github.com/koddas/war-web-project.git
     dest: /tmp/war-web-project
     clone: yes
  
  - name: Build project
    shell: mvn package
    args:
      chdir: /tmp/war-web-project
      
- name: Install Tomcat and launch project
  hosts: prod
  become: yes
  
  tasks:
    - name: Install tomcat
      apt:
        name: tomcat9
        state: present
        
    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started

- name: Copy war file
  hosts: prod
  become: yes
  
  tasks:
    - name: Send file to remote
      synchronize:
        src: /tmp/war-web-project/target/wwp-1.0.0.war
        dest: /var/lib/tomcat9/webapps/wwp-1.0.0.war
      delegate_to: 158.160.0.164