---
- name: Install OpenJDK, Maven, Git
  hosts: web
  become: yes

  tasks:
  - name: OpenJDK
    apt:
     name: default-jdk
     state: present

  - name: Maven
    apt:
     name: maven
     state: present
     
  - name: Git
    apt:
     name: git
     state: present

  - name: Clone git project
    git:
     repo: https://github.com/koddas/war-web-project.git
     dest: /tmp/war-web-project
     clone: yes